name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: cloudflare/go
          ref: cf

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd src
          ./make.bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-build-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./bin/{{ matrix.os }}_{{ matrix.arch }}/
